apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql-service
spec:
  type: NodePort
  ports:
    - port: 80             # service的端口
      targetPort: 3306     # 容器的端口
      nodePort: 30011      # 节点的端口
  selector:
    app: mysql
