apiVersion: v1
kind: Service
metadata:
  labels:
    app: typecho
  name: typecho-service
spec:
  type: NodePort
  ports:
    - port: 80             # service的端口
      targetPort: 80     # 容器的端口
      nodePort: 30010      # 节点的端口
  selector:
    app: typecho
